name: 'Build MAM'
description: 'GitHub Action to build MAM based project'
author: 'Nin Jin <nin-jin@ya.ru>'
inputs:
  module:
    description: 'Path to your module in global MAM scope that you want to build'
    required: true
runs:
  using: 'node12'
  main: '_build.js'
branding:
  icon: 'anchor'
  color: 'blue'
